PACKAGECONFIG:append:rk3288 = " kmsro panfrost"
PACKAGECONFIG:append:rk3328 = " kmsro lima"
PACKAGECONFIG:append:rk3399 = " kmsro panfrost"
PACKAGECONFIG:append:rk3568 = " kmsro panfrost"
PACKAGECONFIG:append:px30 = " kmsro panfrost"
